version: '3'
services:
  VCL:
    image: INFO/VCL
    ports:
      - "80:3000"
    environment:
      - ROOT_URL=https://vcl.ischool.umd.edu

  guacd:
    image: guacamole/guacd
    deploy:
      restart_policy:
        condition: on-failure
